PIG_STICKER_IDS = [
    "CAACAgIAAxkBAAEEDvNiIycKvfBYG2P7XoL4El-zRCX5AAN6AQACFkJrCphFm5ifELSXIwQ",  # NICK WALLOW PIG OK
    "CAACAgIAAxkBAAEEDvViIycV2HyYqNbHVMy4OgSLkoNYIgACdgEAAhZCawqiAV5nfR0-SiME",  # NICK WALLOW PIG FEAR
]